---
- name: Update apt and install dependencies
  apt:
    update_cache: yes
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# - name: Add Docker repository
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
#     state: present

# - name: Update apt and install Docker
#   apt:
#     update_cache: yes
#     name: 
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#     state: present

# - name: Get uname for system
#   shell: uname -s
#   register: uname_s

# - name: Get uname for machine
#   shell: uname -m
#   register: uname_m

# - name: Debug uname_s
#   debug:
#     var: uname_s.stdout

# - name: Debug uname_m
#   debug:
#     var: uname_m.stdout

# - name: Install Docker Compose
#   get_url:
#     url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
#     dest: /usr/local/bin/docker-compose
#     mode: '0755'

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: true

- name: Clone the Git repository
  git:
    repo: 'https://github.com/lucaspereirasouzat/fasterApiNodejs.git'
    dest: /srv/myapp
    version: 'master'

- name: Deploy application with Docker Compose
  command: docker compose up -d
  args:
    chdir: /srv/myapp
